### ISSUE TITLE
Plugin for CycloneDX

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jQA-Idea-Hub#15]
### Feature Descripion
I, as software architect, 
would like to be able to scan CycloneDX documents with jQAsstant,
to that I am able run use the information form CycloneDX to run analysises for my software project.

### Addtional information on the requested Feature
To be able to scan and to import a Software Bill Of Materials (_SBOM_) could our uses enable to use jQAssitant for new uses cases, as we are also able to scan and to analyze Maven repositories.

### How to Test
We should get in touch with the CycloneDX community and ask there, if there is someone willing to play around with it.

### Available Test data
Currently there are not test data available. They must generated or somewhere else found. 

### References

- https://www.cyclonedx.org/
- [CycloneDX workspace at Slack](https://cyclonedx.org/slack/invite)

### Definition of Done for the Implementers
- [ ] Unittests have been written
- [ ] Integration tests have been written
- [ ] Documentation has been written
- [ ] Added a note on the new feature to the release notes

**Comment by StephanPirnbaum** [comment]
Closing for now because of inactivity
