### ISSUE TITLE
Provide Gradle Plugin to scan project

### ISSUE THREAD

**Issue by lostiniceland** [jQAssistant/jQA-Idea-Hub#19]
Currently there is only a custom Gradle plugin to scan a project with JQAssistant. The configuration is much more complex compared to the official maven-plugin.

http://techblog.kontext-e.de/jqassistant-with-gradle/

It would be great if there would be an official Gradle plugin

**Comment by obfischer** [comment]
Duplicate of jQAssistant/jQA-Idea-Hub#7.
