### ISSUE TITLE
rules vs. generated code

### ISSUE THREAD

**Issue by aklemp** [jQAssistant/jQA-Idea-Hub#2]
Hi,

I've stumbled across an issue while testing. Some types are generated and are located in a different source folder. Some of these types are created by 3rd-party tools and I have no control over them. The constraints of jQAssistant are invoked on the complete graph including the generated types. Obviously, there are situations where the constraint is failing for those types (e.g. the `cdi:BeansMustUseConstructorInjection`) but I want them to run on my own code.

One possibility is of course to use none of the available plugin constraints if that problem arises and define new ones with appropriate exclusions. The available constraints could also be templates that can be spezialized with a package, folder or whatever to exclude. The complete analysis could exclude generated code (although I don't like this all-or-nothing approach).

Probably this is a quite common scenario to have hand-written and generated code and different rules apply to them. What would be the way to go?

Kind regards,
  aklemp

**Comment by StephanPirnbaum** [comment]
Closing this as (this is a very old discussion and) we now have means to define custom concepts that provide another concept, i.e. java:GeneratedType. Constraints are then only required to depend on this concept. If this is missing in a specific plugin, please open a ticket there.
