### ISSUE TITLE
Provide Gradle integration

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jQA-Idea-Hub#7]

**Comment by lostiniceland** [comment]
I started working on updating the plugin to run with Gradle 7. It looks like there will be breaking changes, meaning that the plugin will then not run with older Gradle versions anymore. I am proposing a 2.0 to not force anyone to upgrade his build.

**Comment by DirkMahler** [comment]
@lostiniceland If you need support on this topic (from jQA side and based on the experiences with Maven/CLI) please let us know!

**Comment by lostiniceland** [comment]
I have been made aware of a PR which already addressed the Gradle API changes for the plugin.
https://github.com/kontext-e/jqassistant-gradle-plugin/pull/7
It also fixes a chicken-egg problem the plugin-repo has.

**Comment by StephanPirnbaum** [comment]
Closing this as the Kontext-e plugin is currently the way to go.
